### ISSUE TITLE
Warning when >5% deadtime

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#10]
The shifter ANDREA Gozzelino suggested to create sound notification when the deadtime >5%. Right now he has to control it manually from 'rates and dead times' tab of cpmcontroller page.

http://tcds-control-cpm.cms:2050/urn:xdaq-application:lid=100
1. How exactly to calculate the deadtime?
2. In the beginning of the run when deadtime may be 100% - generate notifications only after 5 minutes of run?

**Comment by andreh12** [comment]
In addition to the beginning of the run case, there should be some mechanism to avoid generating sounds all the time when the deadtime goes above and below 5% frequently.

The TCDS CPM application periodically loads /update which returns a json text with all the information (including the configurations). There are two top level items `itemset-latest-nibble-deadtimes` and `itemset-latest-nibble-deadtimes-gated` with keys as follows:

```
{u'Deadtime due to DAQ backpressure': u'0.00',
 u'Deadtime due to TTS': u'0.00',
 u'Deadtime due to firmware sequences': u'0.00',
 u'Deadtime due to software pauses': u'0.00',
 u'Deadtime due to the PM APVE trigger veto': u'0.05',
 u'Deadtime due to the ReTri trigger veto': u'0.00',
 u'Deadtime due to the bunch-mask veto': u'0.98',
 u'Deadtime due to the calibration sequence': u'0.10',
 u'Deadtime due to trigger rules': u'0.02',
 u'Total deadtime': u'1.14'}
```

**Comment by andreh12** [comment]
After some discussion it turns out that there is a flashlist `tcds_cpm_deadtimes` on  `tcds-xaas` port 9945.

**Comment by andreh12** [comment]
In the spirit of #2, I would propose to also include the value of the 'input trigger rate' (sum of `trg_rate_total` and `sup_trg_rate_total` columns in the `tcds_cpm_rates` flashlist) in the message to the shifter, potentially only above a certain second threshold of deadtime or if the input rate exceeds 100 kHz significantly. In the latter case, we should include a remark that the trigger shifter should check why the input trigger rate is so high (e.g. wrong prescale).

**Comment by gladky** [comment]
Deadtime LM introduced in 1.4.2. See example on dev instance:
DAQExpert/?start=2016-11-13T02:59:30&end=2016-11-13T03:01:30
