### ISSUE TITLE
Update specific instruction for FED 1109

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#104]
Same as 1111, keep both

**Comment by mommsen** [comment]
Would it be possible to deploy a new version of the DAQExpert tomorrow (Wed) with this change?

Thanks,
Remi

**Comment by gladky** [comment]
The hotfix is ready to be deployed as release [2.9.5](https://github.com/cmsdaq/DAQExpert/commit/306343dbea0dda860aeff0eb8040c9b726a25ea2)  as soon as there is opportunity to do this.
