### ISSUE TITLE
identification of FEDid causing sync loss in FlowchartCase1

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#13]
FlowchartCase1 seems to search for FEDs in TTS out of sync state for this case which is however unrelated (out of sync FEDs are relevant for flow chart case 3).

Sync loss is the condition when an unexpected event number was received (e.g. event 3 after event 1).

@mommsen confirmed that currently the only way to determine the FEDid which caused a sync loss condition on the RU from flashlist information is to check the RU error message.

Here is a test case: `/DAQExpert//?start=2016-10-26T05:55:59+02:00&end=2016-10-26T05:58:32+02:00`

The corresponding error message from the log4j log is:

`SyncLoss: Caught exception: exception::MismatchDetected 'Mismatch detected: expected evb id runNumber=284006 lumiSection=390 resyncCount=233 eventNumber=4910173 bxId=3388, but found evb id runNumber=284006 *resyncCount=234 eventNumber=1 bxId=94 in data block from FED 583 (CTPPS_TOT)`

In the corresponding json data (see e.g. `/DAQExpert//snapshot?time=%222016-10-26T03%3A56%3A58.178Z%22`) it looks like the message is truncated to 80 characters:

`"errorMsg": "Caught exception: exception::MismatchDetected 'Mismatch detected: expected evb i",`

also in the flashlist dump (`/daqexpertflashlists/flashlists/RU/2016/10/26/3/1477454220204.smile`) this is already truncated:

`"errorMsg" : "Caught exception: exception::MismatchDetected 'Mismatch detected: expected evb i",`

**Comment by andreh12** [comment]
Talking to the XDAQ developers it looks like there is a parameter `maxsize` in the flashlist definition (see daq/xmas/probe/src/common/FlashListMonitor.cc Line 489 ) which defaults to 80 for monitoring fields of type `string`. 

The corresponding flashlist definition file is here: https://github.com/mommsen/evb/blob/master/flashLists/RU.flash .

**Comment by mommsen** [comment]
There's now a XDAQ ticket to increase the limit to 500 characters:
https://svnweb.cern.ch/trac/cmsos/ticket/4227

**Comment by andreh12** [comment]
I was just checking the error message corresponding to this case seen yesterday and the full string (including the `SyncLoss:` at the beginning which seems not to be put into the flashlist item (see https://github.com/mommsen/evb/blob/16e9d56b5ed86584757cddc3ca518eb87aecc67d/include/evb/readoutunit/StateMachine.h#L124 ) and the location in the source `raised at append(.../SuperFragment.cc:32)` and counted 387 characters, so 500 looks good to me.

**Comment by andreh12** [comment]
after updating the flashlist parameters, we have an example test case in `flashlists/RU/2016/12/4/0/1480809927880.smile` :

```
Caught exception: exception::MismatchDetected 'Mismatch detected: expected evb id runNumber=286488 lumiSection=301 resyncCount=4 eventNumber=1247256 bxId=1459, but found evb id runNumber=286488 *resyncCount=5 eventNumber=1 bxId=2206 in data block from FED 548 (ES)' raised at append(/usr/local/src/xdaq/baseline13/trunk/daq/evb/src/common/readoutunit/SuperFragment.cc:32)
```

from the timestamp in the file name, this time corresponds to `Sun Dec  4 01:05:27 CET 2016` (rounded down to nearest second).

The last file corresponding to this occurrence is `flashlists/RU/2016/12/4/0/1480810021592.smile` corresponding to `Sun Dec  4 01:07:01 CET 2016` (rounded down to nearest second)

**Comment by gladky** [comment]
More test cases added for all FC with release c6627a3effbeb352029419e166233438e0c4ed88
