### ISSUE TITLE
add a logic module detecting high deadtime from ReTri

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#140]
The ReTri boards throttle triggers when they detect too much resonance/periodicity in the time pattern of triggers. 

High deadtime from the ReTri boards has happened in the past for fills with a low number of bunches (e.g. 1 or 2 colliding, leading to a L1 rate which is basically a 11 or 22 kHz signal). This happened because the DAQ shifter forgot to add random triggers (which eliminates the periodicity of the triggers).

We should write a module which displays a message to the shifter that deadtime from ReTri is above a (configurable) threshold and that the solution would adding random triggers.

**Comment by gladky** [comment]
Suggestion and description in #150 
Resolved by #151
