### ISSUE TITLE
Operator didn't follow suggestion?

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#162]
Here is the case of `High TCDS trigger input rate`

http://daq-expert.cms/DAQExpert/?start=2017-11-14T13:23:06.448Z&end=2017-11-14T13:29:19.807Z

> High TCDS trigger input rate
> 
> The TCDS trigger input rate is ( last: 102,869.6Hz, avg: 102,712.4Hz, min: 102,480.6Hz, max: 102,945.6Hz) which is high (above 100000.0 Hz). This may be a problem with the L1 trigger: wrong prescale column etc.
> 
> Duration: 1:07 a minute
> Action
> 
>     Ask the trigger shifter to check the prescale column
>     Make an e-log entry
> 
> 

I don't see any corresponding ELOG message around 14:30. Was the prescale column ok? Can we verify this?

**Comment by andreh12** [comment]
from cmswbm (times are UTC, i.e. 13:25 in this table is 14:25 in the DAQExpert):

![image](https://user-images.githubusercontent.com/5003560/32834435-e3cc7272-ca02-11e7-9286-f50ea671dfee.png)

So they went from prescale index 29 to index 8 at 14:25:20 local time and went back to 29 one minute and 10 seconds later (which looks like they realized it does not work well).
