### ISSUE TITLE
HLT rate & BW check

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#17]
DAQDottoressa uses following url to retrieve stream rate: `http://es-cdaq.cms/sctest/stream_summary_delayed.php?setup=?&run=?`

see [StreamRateMonitor](https://svnweb.cern.ch/trac/cms-daqdemo/browser/DAQTools/Monitoring/trunk/DaqDottoressa/StreamRateMonitor.pm)

Hannes:
> Check that physics stream rates are within limits (configurable, different sets for different machine modes, may vary over time, exceptions for special runs, maybe tie to HLT Key or L1/HLT Key). ( finer check in the future: limits may depend on HLT menu, inst. luminosity, prescale-column )

We can also retrieve flag from TSG monitoring (contact Andrea Bocci)

**Comment by gladky** [comment]
As Srecko suggested ES will be queried to get the HLT rate.

example request:
http://es-cdaq.cms/sc/php/stream_summary_last.php?setup=cdaq&run=284666&unit=events

example response:
`{"219":{"ALCALUMIPIXELS":47.190047190047,"ALCAPHISYM":0,"Calibration":79.365079365079,"DQM":6.8640068640069,"DQMCalibration":7.9365079365079,"DQMEventDisplay":18.618618618619,"DQMHistograms":612.44101244101,"EcalCalibration":79.365079365079,"Error":0,"ExpressCosmics":19.004719004719,"HLTRates":612.44101244101,"L1Rates":612.44101244101,"NanoDST":5.7915057915058,"Physics":71.600171600172,"RPCMON":27.627627627628}}`

from Srecko:
>  Above numbers are per lumisection. I changed the script now to normalize to a second. Output is in Hz and Bytes/s.
There is filtering so that last finished lumisection only is retrieved (actually I put threshold at 99%, which should help if there is small number of FUs lagging behind).

**Comment by gladky** [comment]
We can also retrieve flag from TSG monitoring (contact  Andrea Bocci)

**Comment by andreh12** [comment]
The DAQDoctor had event rate limits which depend on `LHC_MACHINE_MODE` (the limitation comes mainly from the output bandwidth, higher event sizes during heavy ion physics translate to lower event rates at the same bandwidth compared to proton proton physics -- nevertheless it is also good to watch the event rate e.g. during cosmics running where the bandwidth is typically far from the maximum the system can handle).

Ideally, we would store these limits outside the code, e.g. in a properties files. @gladky , where should we store such limits ?

**Comment by mommsen** [comment]
If you need a test case for (way) too high output rate, we just had one:
http://daq-expert.cms/daq2view-react/index.html?setup=cdaq&time=2017-10-26-22:35:29

**Comment by andreh12** [comment]
thanks -- yes, this one is indeed high :-)

**Comment by andreh12** [comment]
as discussed with @hsakulin , we will implement two different modules for high and very high HLT output bandwidth. 
* the two will have slightly different diagnostic messages 
* the result of their `satisfy()` methods can be used individually by other logic modules (e.g. do some actions only if the HLT output bandwidth is 'very high')

**Comment by gladky** [comment]
Ready to review as pull request #144

**Comment by gladky** [comment]
There were 2 long lasting cases (~8h) where the Hight HLT output bandwidth was fluctuating around 4.5 GB/s, reaching 5.5 GB/s. This yielded 49 alarms during the weekend.

http://daq-expert-dev.cms/DAQExpert/?start=2017-11-18T10:48:29.422Z&end=2017-11-19T00:07:22.139Z

http://daq-expert-dev.cms/DAQExpert/?start=2017-11-19T19:57:21.134Z&end=2017-11-20T05:44:30.270Z

It looks like even with too high HLT rate there were no problems and we were running smoothly. Should we adjust the threshold or these results are desired?

**Comment by andreh12** [comment]
we currently have HLT conditions different from high energy pp running, @mommsen could probably suggest an updated value for the threshold

**Comment by mommsen** [comment]
I think we should not update the thresholds. That the HI community decided to stress the system beyond its specifications does not mean that we should not warn about it.

Cheers,
Remi

**Comment by gladky** [comment]
Thanks Remi.

**Comment by mommsen** [comment]
This morning, we had several instances where the HLT output rate exceeded 6 GB/s, e.g. run 314860 LS 9-14. However, there was no message about this in the DAQExpert. Can you please investigate why this check did not fire?

**Comment by andreh12** [comment]
The relevant code (e.g. https://github.com/cmsdaq/DAQExpert/blob/master/src/main/java/rcms/utilities/daqexpert/reasoning/logic/failures/HltOutputBandwidthTooHigh.java ) is not part of the currently running release (`2.9.16-splashes`) but is part of `2.9.17`. 

Deploying version 2.9.17 should fix the issue. At the same time we should also deploy the most recent version of the DAQAggregator which we run already for other setups (see https://github.com/cmsdaq/DAQExpert/issues/170#issuecomment-382351347 ).

**Comment by andreh12** [comment]
Version `2.9.19` has been deployed today, so we can close the issue (please reopen if this happens again).
