### ISSUE TITLE
Special instructions: Tcds and pixel

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#177]
From the [Shifter Bulletin](https://twiki.cern.ch/twiki/bin/viewauth/CMS/ShiftNews)   

>    * If TCDS is Red or Green recycled then Green recycle Pixels and call PIXEL DOC (Hannes, on request by Sudan, 4 Oct, 2017). Note that this basically means that you cannot use the Level-0 Automator for the time being.

**Comment by gladky** [comment]
Is is up to date?

**Comment by hsakulin** [comment]
I have asked the question to a Pixel expert. H.

**Comment by gladky** [comment]
to be removed - confirmed by PIXEL
