### ISSUE TITLE
Special instructions: FED in warning or busy

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#180]
> If *any FED is in warning or busy*, check with the L1 trigger shifter if the trigger rate is too high (&gt;100 kHz). (Remi, Aug 18 2017)

We do have 2 modules related to this.

- LM "Fed Stuck" checks if FED is in Warning or Busy + if partition is in Warning or Busy + if DAQ is in runblockded
- LM "RateTooHigh" checks rate from fedBuilderSummary (average rate taken from EVM) - the threshold currently is set to 100 kHz. 

In case they both fire we show RateTooHigh that will yield the instructions:

```
1. Ask the trigger shifter to check the inputs to the L1 trigger
2. Make an e-log entry
```

The special instruction is compatible with what expert suggests. If there are no comments to that I will remove it from the list of special instructions soon.

**Comment by mommsen** [comment]
This instructions can be removed. They pre-date the inclusion of the LM "RateTooHigh" check.

**Comment by gladky** [comment]
Thank you @mommsen for confirmation, closing
