### ISSUE TITLE
Special instructions: PIXEL lag in configuring

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#191]
From shifter bulletin:
>   * *PIXEL*
>       (Jeroen Hegeman & Stefanos Leontsinis, 20170530)
>       * If adding the Pixels to the RUN but there is a large lag in configuring. Add in the Run, destroy the Pixels and then green recycle. This will prevent them from being stuck HALTED
>

**Comment by gladky** [comment]
1. is this up to date?
2. If so do we want Expert detect that case?

**Comment by jhegeman** [comment]
Hi Maciej,

Those are not my instructions (nor Stefanos's, actually). They seem to have been added by one of our DAQ shifters:
https://twiki.cern.ch/twiki/bin/rdiff/CMS/ShiftNews?rev1=1405;rev2=1404

Cheers,
Jeroen

**Comment by jhegeman** [comment]
Actually, when I try to translate that comment/instruction, I get the impression that the shifter in question did not quite appreciate some of the L0 FM functionality. If you ask me, I would simply forget about that instruction. (But better double-check with the pixel experts to be sure.)

**Comment by gladky** [comment]
to be removed - confirmed by PIXEL
