### ISSUE TITLE
Special instructions: Pixel OOS

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#192]
>       * If PIXEL FED is OOS:
>          * Try Pause and Resume.
>          * If this doesn't solve the problem: stop the run, green recycle PIXEL and start new run (recovery button of L0A with tick on PIXEL green recycle).
>          * If also this does not resolve the problem: stop the run, red recycle PIXEL and start new run (recovery button of L0A with tick on PIXEL red recycle).
>

**Comment by gladky** [comment]
Current default instructions coming from "Out of sequence data received" (includes Pixel)

> 
> 1. Try to recover (try up to 2 times)
> 1. StopAndStartTheRun
> 1. Problem not fixed: Call the DOC of {{PROBLEM-SUBSYSTEM}} (subsystem that caused the SyncLoss)
> 1. Problem fixed: Make an e-log entry. Call the DOC {{PROBLEM-SUBSYSTEM}} (subsystem that caused the SyncLoss) to inform about the problem

**Comment by gladky** [comment]
We could introduce PIXEL specific instructions for this case:

1. Try Pause and Resume.
1. Problem not fixed: stop the run, green recycle PIXEL and start new run 
1. Problem still not fixed: stop the run, red recycle PIXEL and start new run
1. Problem fixed: Make an e-log entry.

Note:
- I removed the part "(recovery button of L0A with tick on PIXEL green recycle)." as I assume it's obvious to shifters
- I added standard make an e-log entry

**Comment by gladky** [comment]
Please confirm that's up to date.

**Comment by hsakulin** [comment]
Proposed changes are fine according to Benedikt.

**Comment by gladky** [comment]
Introduced with 2.13.1, moved to section "covered by expert" in bulletin board
