### ISSUE TITLE
Special instructions: PIXEL rates after pause-resume

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#194]
> * After the automatic pause-resume transitions at the beginning of stable beams, please check the data rates from pixels (in the DAQView). In case these remain at the same levels as with HV off, this means that the HV bit was not picked up correctly. In that case pixel require a pause and resume of the run. Please double-check that the pixel HV has ramped up correctly with the DQM shifter (by looking at the pixel occupancy plots).

**Comment by gladky** [comment]
1. Is this up to date?
1. if so shall we make this check in expert? if yes we would need to include information whether HV has ramped up or not.

**Comment by hsakulin** [comment]
AFAIK the problems with enabling pixels after HV ramp have been fixed. I think we can drop these instructions.

**Comment by gladky** [comment]
Removed.
