### ISSUE TITLE
Special instructions: HCAL FED 1111 and 1109

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#197]
From shifter bulletin:

> * *HCAL*
>     * If FED 1111 sends out-of-sequence data (DAQ going to RunBlocked), just stop the run and start a new one (or click Recover Run without specifying a subsystem to recycle). If the same problem is now (from Sept 2nd) in FED 1109, take the same action (stop/start) and report in the ELOG. (Emilio, Sept 2nd 2017)

**Comment by gladky** [comment]
Currently we have specific instructions for FED 1111 and 1109

> 1. StopAndStartTheRun
> 2. Problem not fixed: Call the DOC of {{PROBLEM-SUBSYSTEM}} (subsystem that caused the SyncLoss)
> 3. Problem fixed: Make an e-log entry.
> 4. Call the DOC {{PROBLEM-SUBSYSTEM}} (subsystem that caused the SyncLoss) to inform about the problem

**Comment by andreh12** [comment]
This should be this message: https://github.com/cmsdaq/DAQExpert/blob/54b535439131c3b05115695d38e3375009e1c081/src/main/java/rcms/utilities/daqexpert/reasoning/logic/failures/backpressure/OutOfSequenceData.java#L49-L53

and the corresponding logic: https://github.com/cmsdaq/DAQExpert/blob/54b535439131c3b05115695d38e3375009e1c081/src/main/java/rcms/utilities/daqexpert/reasoning/logic/failures/backpressure/BackpressureAnalyzer.java#L506-L515

but still good to know if the instructions should be kept or not.

**Comment by gladky** [comment]
It seems that we might instruct operator unnecessarily to call the DOC.

1. HCAL, would like to adjust the instructions?

**Comment by andreh12** [comment]
I contacted them by email (with you in Cc:)

**Comment by hsakulin** [comment]
please send a reminder if you did not get a reply.

**Comment by andreh12** [comment]
@jkunkle can you comment on this issue ?

**Comment by jkunkle** [comment]
Hi, I didn't realize that there was a second similar thread.  We have not seen problems with these specific FEDs (or such a problem from any HCAL FEDs) this year.  Therefore I think you can remove these special instructions

**Comment by gladky** [comment]
removed
