### ISSUE TITLE
Special instructions: FED 1404

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#198]
> * If FED 1404 stop sending data, first try stop run and Red and green recycle trigger if it doesn't work then you should call directly the GT DOC 160862 (Jose Ruiz, 29-05-2017)

**Comment by gladky** [comment]
1. Is this up to date?
1. Is "stop sending data" equivalent of "FED stuck"?

**Comment by gladky** [comment]
contacted jose.ruiz@cern.ch

**Comment by andreh7** [comment]
FED 1404 is `uGT` (micro Global Trigger) according to #182

**Comment by andreh12** [comment]
FED 1404 is uGT (micro Global Trigger) according to #182

**Comment by dinyar** [comment]
Hi,
I don't think uGT needs to be treated specially anymore. I remember the DAQ expert already has instructions for such a situation (i.e. FED xyz stops sending data, after a while DAQ exerts backpressure on some other FED), can you remind me what this was?

Cheers,
Dinyar

**Comment by gladky** [comment]
Do you mean this:

> RU {{AFFECTED-RU}} is stuck waiting for FED {{PROBLEM-FED}}. Problem FED(s) belong(s) to partition {{PROBLEM-TTCP}} in {{PROBLEM-SUBSYSTEM}} subsystem. This causes backpressure at FED {{AFFECTED-FED}} in other FED-builder {{AFFECTED-FED-BUILDER}} of subsystem {{AFFECTED-SUBSYSTEM}}. Note that there is nothing wrong with backpressured FED {{AFFECTED-FED}}

with a recovery action:


> 1. Try to recover: Stop the run
> 1. Red & green recycle the subsystem {{PROBLEM-SUBSYSTEM}} (whose FED stopped sending data)
> 1. Start new Run (Try 1 time)
> 1. Problem fixed: Make an e-log entry. Call the DOC of the subsystem {{PROBLEM-SUBSYSTEM}} (whose FED stopped sending data) to inform
> 1. Problem not fixed: Call the DOC for the subsystem {{PROBLEM-SUBSYSTEM}} (whose FED stopped sending data)

from [RUStuckWaitingOther](https://github.com/cmsdaq/DAQExpert/blob/master/src/main/java/rcms/utilities/daqexpert/reasoning/logic/failures/backpressure/RuStuckWaitingOther.java) LM

**Comment by dinyar** [comment]
Yes, that's it. This can be used also for uGT (1404), I don't remember exactly what triggered that entry in the shifter instructions, but we haven't had any readout problems with the uGT in the past few months that would warrant special instructions.

**Comment by gladky** [comment]
In this case this will be deleted from shifter bulletin board. I guess there is no need to keep it in section "deprecated" or "outdated", right @hsakulin ?

**Comment by gladky** [comment]
removed.
