### ISSUE TITLE
Special instructions: TOTDET deadtime

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#199]
>    * If the run gets deadtime due to totem (TOTDET), this is likely a trigger rate issue. Check the rates coming from sub detecteors to understand what is the problem (Matthieu Marionneau 12-06-2017)

**Comment by gladky** [comment]
Currently we detect deadtime of each partition (including TOTDET) and we report:

> Deadtime of partition(s) {{PROBLEM-PARTITION}} in subsystem(s) {{PROBLEM-SUBSYSTEM}} is {{DEADTIME}} the threshold is X%

- Current threshold is set to 2%
- We do not suggest any recovery action.

**Comment by gladky** [comment]
1. Is this up to date?
1. shall we include this in expert?

**Comment by jjhollar** [comment]
Hi again,

Please see the other ticket (https://github.com/cmsdaq/DAQExpert/issues/184) - it's the same issue I mentioned where these are 2 of the slowest FEDs, so any time the trigger rate goes crazy they will be the ones appearing to cause large deadtime by throttling to a little more than 100kHz L1A rate. 

This is still up to date. I think it's up to you if it should be included in the DAQ expert separately, or if you think it's already covered by the high trigger rate alarms. Personally my preference would be for the DAQ expert to always show the denominator when reporting deadtime as a percentage - there's a big difference between 95% of 100kHz and 95% of 40MHz :) 

Jonathan

**Comment by gladky** [comment]
Covered by 2 LM monitoring TCDS rate:

### HighTcdsInputRate

The TCDS trigger input rate is high: {{TCDS_TRIGGER_INPUT_RATE}}

1. Ask the trigger shifter to check the prescale column
1. Make an e-log entry

threshold: > 100 kHz

### VeryHighTcdsInputRate

The TCDS trigger input rate is very high: {{TCDS_TRIGGER_INPUT_RATE}}

1. Ask the trigger shifter to check the inputs to the L1 trigger (noisy towers, failed links)
1. Make an e-log entry


threshold: > 200 kHz + dominates HighTcdsInputRate
