### ISSUE TITLE
Special instructions: HCAL blocks the run

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#204]
>    * *HCAL* when it blocks the run (e.g. TTS "BUSY", "WARNING", etc):
>       * If we are during stable beams:
>          * Stop/Start (if needed one more time)
>          * Red-Recycle
>          * If it does not work, call the HCAL DOC
>       * If we are not during stable beams:
>          * Do NOT stop the run and call the HCAL DOC
>

**Comment by gladky** [comment]
Currently in expert it would be identified as FED stuck and default recovery suggestion would be proposed:

> 1. StopAndStartTheRun with <<RedRecycle::{{SUBSYSTEM}}>> and <<GreenRecycle::{{SUBSYSTEM}}>> (try up to 2 times)
> 1. Problem fixed: Make an e-log entry. Call the DOC of the subsystem {{SUBSYSTEM}} to inform
> 1. Problem not fixed: Call the DOC for the subsystem {{SUBSYSTEM}}

Description of the problem:

> TTCP {{TTCP}} of {{SUBSYSTEM}} subsystem is blocking triggers, it's in {{TTCPSTATE}} TTS state, The problem is caused by FED {{FED}} in {{FEDSTATE}}

Note that:

- this would be triggered only if TTCPSTATE in (warning or busy)
- daq not in runblocked state

**Comment by gladky** [comment]
contacted HCAL experts

**Comment by jkunkle** [comment]
I do not think that we need any special instructions for the case when HCAL blocks the run.  This was probably left over from last year and should not be needed anymore

**Comment by hsakulin** [comment]
Then we just have to remove the instructions.

**Comment by gladky** [comment]
removed
