### ISSUE TITLE
Special instructions: RCT FEDs

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#205]
>    * if *RCT* (FED 1354, 1356, 1358) in 100% Warning during stable beams: issue a TTCHardReset
>      If outside stable beams and during office hours, call L1 DOC 161958 (backup=160862) and DAQ DOC 76600 before issuing a TTCHardReset.

**Comment by gladky** [comment]
We do not have any module that monitors FED warning only but it would be easy to add.

- [ ] is it up to date?
- [ ] shall we add this check?

**Comment by gladky** [comment]
@dinyar could you please comment on this?

**Comment by dinyar** [comment]
Hi,
I think this is from when CaloL1 (at the time their partition name was RCT) regularly got backpressure first and therefore was often blamed for downtime. Given that DAQ expert now detects that condition I think that it can be removed.

Cheers,
Dinyar

**Comment by gladky** [comment]
removed
