### ISSUE TITLE
Special instructions: TRACKER TOB FED 434

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#206]
>  * If any issues with *TRACKER* TOB FED 434, please red-recycle and reconfigure the TRACKER. If FED 434 give error again, take it out immediately. Call the Tracker DOC.

**Comment by gladky** [comment]
- [ ] is this up to date?
- [ ] could you please be more specific on "any issues" - does this rule cancel all other reasoning: FED stuck, FED generates backpressure etc?

**Comment by erikbutz** [comment]
These instructions should be removed. This should be covered by other instructions in the DAQ expert as the FED will be stuck in WARN or BUSY and there the instructions already include a red recycle. 

No instructions to directly exclude FEDs should be in the DAQ expert at this point.

**Comment by hsakulin** [comment]
The instructions should be removed.

**Comment by gladky** [comment]
removed
