### ISSUE TITLE
Special instructions: ECAL HCAL TRIGGER Link Alignment problem

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#207]
>    * *ECAL or HCAL + TRIGGER* If you see errors like this: <span data-mce-mark="1" style="background-color: transparent;">%ATTACHURL%</span>/trigerr.png red-recycle the indicated calorimeter (ECAL/HCAL).

- [ ] is this up to date?
- [ ] shall we introduce it to expert?

**Comment by gladky** [comment]
@giacomoCucciati could you please comment on this one?

**Comment by giacomoCucciati** [comment]
Hello, unfortunately I have no clues on this error. I am not sure I have ever seen it.

**Comment by andreh12** [comment]
searching for `Input Link Alignment Status` in the `triggerpro` logs I saw that the last occurrence was `Thu 2017-10-26 20:12:55` (see e.g. http://daq-expert.cms/daq2view-react/?setup=cdaq&time=2017-10-26-20:12:55 ).

There is a corresponding snapshot from a few seconds later `/daqexpertflashlists/flashlists/pro/cdaq/LEVEL_ZERO_FM_SUBSYS/2017/10/26/18/1509041578866.json.gz` which contains such an error message in the `ERROR_MSG` field of the `TRG` subsystem.

However, as  far as I can tell do we not propagate the `ERROR_MSG` field from the flashlists into the snapshot in the DAQAggregator so we would not be able to identify this condition at the moment.

**Comment by hsakulin** [comment]
The ERROR message is shown here: 
https://twiki.cern.ch/twiki/pub/CMS/ShiftNews/trigerr.png

Since we cannot detect the situation, I think the instructions should stay on the Twiki.

**Comment by andreh12** [comment]
we could detect it but we would need to add the `ERROR_MSG` field from the flashlists to the DAQAggregator snapshot (see my comment above)

**Comment by gladky** [comment]
Leaving in shifter bulletin board.
