### ISSUE TITLE
Special instructions: TRACKER error upon GR

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#210]
>    * During inter-fills only: if the tracker goes into error upon green-recycle, don't red-recycle, but call the tracker DOC.

- [ ] is this up to date?
- [ ] if so shall we introduce it to expert?

**Comment by andreh12** [comment]
contacted a tracker expert by email

**Comment by andreh12** [comment]
tracker expert answered:
>  No, this is not applicable anymore

**Comment by gladky** [comment]
Thank you @andreh12, I will remove this from shifter bulletin in one batch update together with others.
