### ISSUE TITLE
Special instructions: general - problem in TCDS/FEROL SlinkExpress

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#216]
>  If you observe a problem in TCDS/FEROL SlinkExpress during normal working hours, please keep the system in that state and call the DAQ oncall 76600(added by A.Holzner 2014-02-13)

- [ ] up to date?
- [ ] shall be introduced to expert?

**Comment by jhegeman** [comment]
This has been outdated since 2015...

**Comment by gladky** [comment]
Thank you, I will remove it from shifter bulletin.
