### ISSUE TITLE
Special instructions: general - LHC clock unstable - everybody in halted

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#217]
> * During ramping (up or down), LHC clock is unstable. If the run crashes, put everybody in halted and wait a stable situation to start/ask the shift leader what to do.

- [ ] up to date?
- [ ] shall be introduced to expert?

**Comment by mommsen** [comment]
I would remove it. Currently, CMS tries to run during the ramp, although ECAL has still problems. But there are now special instructions for this in #187.

**Comment by gladky** [comment]
removed
