### ISSUE TITLE
add support for a separate threshold during machine development in module CloudFuNumber

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#226]
as suggested by @geneguvo

**Comment by gladky** [comment]
With this hotfix I propose to change the title of the condition from camel case to sth more human readable. 

![screen shot 2018-06-12 at 11 02 10](https://user-images.githubusercontent.com/1798923/41280793-207178d6-6e30-11e8-90b3-a9edb70b5747.png)


Just update this:
> this.name = "CloudFUnumber";

**Comment by andreh12** [comment]
can we have spaces in the name ? If so I would propose `Cloud FU number`. Or `# cloud FUs` ? or `number of cloud FUs` ?

**Comment by gladky** [comment]
Yes we can. This field is used in the names of conditions in the browser and in the dashboard. You can see most of them are with spaces. I would personally go for 

> Too many FUs in cloud mode

as it tells you what's the problem.

**Comment by andreh12** [comment]
ok, changed in 76450a1

**Comment by andreh12** [comment]
earlier tickets about this module: #131 (initial proposal for the module) and #163 (holdoff timer)

**Comment by andreh12** [comment]
The commits above do not introduce a second separable threshold but instead treat MD/TS periods like we have been treating interfill periods far away from stable beams so far (effectively no limit on the fraction of cloud FUs).

**Comment by andreh12** [comment]
released in https://github.com/cmsdaq/DAQExpert/releases/tag/2.10.16

**Comment by andreh12** [comment]
forgot to add that `mvn test` on master (88cc5f0) reports: `Tests run: 186, Failures: 0, Errors: 0, Skipped: 21`

and `mvn integration test` reports `Tests run: 13, Failures: 0, Errors: 0, Skipped: 2`.
