### ISSUE TITLE
Add hold-off to 'Too high HLT output bandwidth'

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/DAQExpert#233]
DAQExpert regularly reports 'Too high HLT output bandwidth' when a run is started during stable beams. This is due to the processing of the backlog accumulated on the RAMdisk. I would suggest to add the same hold-off period as applied for reporting on the CPU load implemented in #186.

Remi

**Comment by andreh12** [comment]
all 209 enabled tests pass with the code committed above

**Comment by andreh12** [comment]
This is now in 2.13.4 which has been deployed.
