### ISSUE TITLE
Detect sub-system stuck in FixingSoftError (LengthyFixingSoftError LM)

### ISSUE THREAD

**Issue by hsakulin** [cmsdaq/DAQExpert#3]
DAQExpert should detect soft error recovery taking too long or failing and warn the shift crew.

For a recovery taking too long see for example the following instance in the RunInfo timeline (not posting the host port to github):

?sessionId=280544&time=1465808149336

**Comment by gladky** [comment]
Implemented in branch [soft-error-count](https://github.com/cmsdaq/DAQExpert/tree/feature/soft-error-count). We need to come up with recovery suggestions.

**Comment by gladky** [comment]
As @mommsen suggested:
Call the DOC of subsystem {{SUBSYSTEM}}, and ask the DCS shifter to check the status of subsystem {{SUBSYSTEM}}

**Comment by andreh12** [comment]
I see that the message described in https://github.com/cmsdaq/DAQExpert/issues/3#issuecomment-333084411 is implemented in 88a2d780 (in `LengthyFixingSoftError.java`) and 43e5482c (StuckAfterSoftError.java) both which have been merged into the `dev` branch as part of merging the https://github.com/cmsdaq/DAQExpert/tree/feature/soft-error-count branch into `dev` yesterday.
