### ISSUE TITLE
Monitor CPU usage

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#44]
- [ ] RU - source?
- [ ] BU - source?
- [ ] FU - only aggregated average avaialbe (see quote below)

Srecko:
> 
> It's calculated only for FUs and not in a way that can be matched to a FU hostname, i.e. just for calculating average.
> Aggregated average for the whole filterfarm is available from a php script and also from Oracle DB, which is preferred place to look at this information. I can also put this in a script (to get you the latest value) if you prefer it that way.

> CPU usage, you can take a look at /nfshome0/smorovic/oracle/cpu.py which retrieves the latest cpu usage value from database.

**Comment by andreh12** [comment]
We should focus on the FUs and warn if the CPU load is above 90%.

**Comment by gladky** [comment]
@andreh12 HltInfo class in commit e44b304

**Comment by gladky** [comment]
released with 2.9.17
