### ISSUE TITLE
logic module to catch unidentified problems

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#59]
discussing with @gladky we propose the introduction of a logic module which fires when
* there is no (trigger) rate when rate is expected
* no other logic module identifying know error conditions has fired

This will allow to find such cases in the notification manager archive more easily and help 
to improve the software to identify not yet caught cases in the future.

More specifically, this new logic module will check whether `NoRateWhenExpected` has fired but no logic module inheriting from `KnownFailure` has identified a problem.

**Comment by gladky** [comment]
We have the test case of unidentified-problem which was caught on development instance:

http://daq-expert-dev.cms/nm/archive?source%5B%5D=UnidentifiedFailure&page=1

I suggest we change the suggested messages from

> Reason for no trigger rate could not be identified
> 1. make an elog entry

to 
> Trigger rate is zero. The problem could not be identified.
1. recover the system according to instructions from shifter bulletin board 
2. make an elog entry

**Comment by gladky** [comment]
Introduced with [2.4.0](https://github.com/cmsdaq/DAQExpert/tree/release/2.4.0)
