### ISSUE TITLE
separating persistent id from logic module execution order

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#61]
as discussed with @gladky : currently the execution order of logic modules is tightly coupled to the persistent id used in the database (both are defined by the definition order in the enum `LogicModuleRegistry`). In order to go ahead with #59 we need to separate them.

For this we add a property `runOrder` to class `LogicModule` with which the running order of the modules can be explicitly defined, independently from the order of definition in  `LogicModuleRegistry`.

**Comment by gladky** [comment]
introduced in [2.4.0](https://github.com/cmsdaq/DAQExpert/tree/release/2.4.0)
