### ISSUE TITLE
detect when a subsystem is stuck in SoftErrorRecovery (StuckAfterSoftError LM)

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#64]
e.g. for more than one minute

**Comment by gladky** [comment]
Implemented in branch [soft-error-count](https://github.com/cmsdaq/DAQExpert/tree/feature/soft-error-count). We need to come up with suggestions.

Example test case:
http://daq-expert-dev.cms/DAQExpert/?start=2017-06-02T21:21:23.007Z&end=2017-06-02T21:29:48.338Z

**Comment by andreh12** [comment]
the twiki for the DAQ shifter (CMS/ShiftNews) says in particular for ES: 

> ES may ask for consecutive SoftErrorRecovery every ~10 seconds. What to do: 
> 1. Stop the run and re-start it. 
> 1. If 1) doesn't work and DAQ is in the same condition as before, stop the run and red-recycle ES.

**Comment by gladky** [comment]
We could include this in next release if we come up with suggestions for this problem.

**Comment by gladky** [comment]
As remi suggested:
Call the DOC of subsystem {{SUBSYSTEM}}, and ask the DCS shifter to check the status of subsystem {{SUBSYSTEM}}

**Comment by andreh12** [comment]
I see that the message described in https://github.com/cmsdaq/DAQExpert/issues/64#issuecomment-333084272 is implemented in 88a2d780 (in `LengthyFixingSoftError.java`) and 43e5482c (StuckAfterSoftError.java) both which have been merged into the `dev` branch as part of merging the [soft-error-count](https://github.com/cmsdaq/DAQExpert/tree/feature/soft-error-count) branch into `dev` yesterday.

**Comment by gladky** [comment]
@andreh12, yes, according to conversation in #65.
