### ISSUE TITLE
add link to run information in CMSWBM on run popup window

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#7]
When clicking on the Run NO bar in the DAQExpert, one gets a popup window with the run number.

Would it be possible to add a link to the run summary information for this run in CMSWBM 
(relative URL /cmswbm/cmsdb/servlet/RunSummary?RUN=XXXXXX) ?

**Comment by gladky** [comment]
Link introduced in 1.4.3 (check deployed on dev instance). Place different than proposed. For consistency placed in upper right dropdown 'external tools' - next to run info button.
