### ISSUE TITLE
add support for displaying duration of an event

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#8]
It would be nice to see the duration of an event in the 'Event details' popup of the browser.

As a first step (as far as I understood) could RaportAPI also add the value returned by `Event.getDuration()` to `result` (around here https://github.com/cmsdaq/DAQExpert/blob/dev/src/main/java/rcms/utilities/daqexpert/servlets/RaportAPI.java#L73).

**Comment by gladky** [comment]
Introduced in 1.4.6. Next step would be to add sums of visible events on the right site of browser (see #16). You think it would be useful?

**Comment by andreh12** [comment]
thanks a lot !

Good idea, the sum of the duration of visible events is definitively useful for accounting purposes (e.g. to answer "how much time did we lose last week ?").
