### ISSUE TITLE
Test cases #2: verification after merging recent features

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#83]
### case 4:

http://daq-expert.cms/daq2view-react/index.html?setup=cdaq&time=2017-06-14-15:56:04

- 'Partition problem': Partition TIBTID in TRACKER subsystem is in OUT_OF_SYNC TTS state. It's blocking trigger.

- 'Corrupted data received': Run blocked by corrupted data from FED [841,843] received by RU ru-c2e12-30-01.cms which is now in failed state. Problem FED belongs to partition CSC+ in CSC subsystem This causes backpressure at FED 1386 in partition MUTFUP of TRG

- 'RUs failed': 1 RUs (ru-c2e12-30-01.cms) are in failed state for an unidentified reason. The most often occurring ((1 times) error message is: Caught exception: exception::DataCorruption 'Received a corrupted event 1 from FED 843 (CSC): mismatch of FED id in FEROL header: expected FED 843 (CSC), but got 4095, and FED header "sourceId" 4095 does not match the FED 843 (CSC) found in FEROL header.  In addition, the FED trailer indicates that the FED id is not expected by the FEROL (FED trailer F bit is set)' raised at reportErrors(/usr/local/src/xdaq/baseline14/trunk/daq/evb/src/common/readoutunit/FedFragment.cc:541)

1 and 2 are correct, but again ru-failed is satisfied and may confuse.

### case 5:

http://daq-expert.cms/daq2view-react/index.html?setup=cdaq&time=2017-06-27-10:20:36

- 'FED stuck' TTCP HF of HF subsystem is blocking trigger, it's in WARNING TTS state, The problem is caused by FED (1121 behind pseudo FED 11120) in (FED has no individual TTS state, WARNING @ its pseudo FED)

- 'Corrupted data received' for 2017-06-27T08:20:36Z:
Run blocked by corrupted data from FED 622 received by RU ru-c2e14-29-01.cms which is now in failed state. Problem FED belongs to partition EB- in ECAL subsystem This causes backpressure at FED 1120 in partition HF of HF

- 'RUs failed' for 2017-06-27T08:20:36Z:
1 RUs (ru-c2e14-29-01.cms) are in failed state for an unidentified reason. The most often occurring ((1 times) error message is: Caught exception: exception::DataCorruption 'Received a corrupted event 6090420 from FED 622 (ECAL): inconsistent event size: FED trailer claims 2928 Bytes, while sum of FEROL headers yield 3056.  In addition, the FED trailer indicates that a wrong FED CRC checksum was found by the FEROL (FED trailer R bit is set)' raised at reportErrors(/usr/local/src/xdaq/baseline14/trunk/daq/evb/src/common/readoutunit/FedFragment.cc:541)

Which is correct? 1 or 2? ru-failed again is giving not precise information.

**Comment by hsakulin** [comment]
case 4: This is s strange case with multiple problems overlayed. It would be good to add the detailed error message of 3 also to 2.
We should check if we can make RU-failed more specific so that it does not trigger in this case. 

case 5: 2 is correct. FED stuck should not trigger because 1120 is backpressured.

**Comment by andreh12** [comment]
on @hsakulin 's comment to case 4: I'd be happy to have the `RuFailed` module fire only if there is no other `KnownFailure` firing (and at least one RU is in failed state), similarly to `UnidentifiedFailure`, but I understood that the current strategy is not to make the modules depend on each other too much (and rather rely on the `usefulness` to determine which one should be displayed).

Let me know if we can relax the requirement of (almost) no dependencies on the results of other logic modules and I can add the above requirement to the `RuFailed` module.

**Comment by gladky** [comment]
@hsakulin I've updated the FC5 to require that there is zero FEDs backpressured. All other FC5 tests are passing after the change. Test case 5 is no longer returning fed-stuck.

**Comment by gladky** [comment]
Thank you for you're input. Expectations from the test cases are clear to me now. The issue with RuFailed I'm moving to individual issue #87
