### ISSUE TITLE
Test cases #3: verification after merging recent features

### ISSUE THREAD

**Issue by gladky** [cmsdaq/DAQExpert#88]
After including back the legacy FC1 and FC2 and make them run when new OutOfSync and CorruptedData LM are not satisfied to cover more cases I have few test cases to confirm. Here they are overlapping with FedStuck and PartitionProblem. Could you please confirm which problem is correct one to report?

### Case 6

http://daq-expert.cms/daq2view-react/index.html?setup=cdaq&time=2017-06-17-14:44:51

- 'FED stuck': TTCP TOTDET of CTPPS_TOT subsystem is blocking trigger, it's in BUSY TTS state, The problem is caused by FED 582 in BUSY
- 'Out of sequence data received': Run blocked by out-of-sync data from FED 582, RU ru-c2e14-10-01.cms is in syncloss. Problem FED belongs to TTCP TOTDET in CTPPS_TOT subsystem. Original error message: 'Received an event out of sequence from FED 582 (CTPPS_TOT/CTPPS): Received a duplicate event number 0

### Case 7:

http://daq-expert.cms/daq2view-react/index.html?setup=cdaq&time=2017-06-20-14:56:45

- 'Partition problem' : Partition TOTDET in CTPPS_TOT subsystem is in OUT_OF_SYNC TTS state. It's blocking trigger.

- 'Out of sequence data received': Run blocked by out-of-sync data from FED 582, RU ru-c2e14-10-01.cms is in syncloss. Problem FED belongs to TTCP TOTDET in CTPPS_TOT subsystem. Original error message: 'Received an event out of sequence from FED 582 (CTPPS_TOT/CTPPS): Received a duplicate event number 0

**Comment by mommsen** [comment]
Both cases are diagnosed correctly. 

However, I wonder why case 7 is classified as 'partition problem' while case 6 is 'FED stuck'. The only difference is that in case 6 the FED 582 went into BUSY, while in case 7 it is OUT_OF_SYNC.

**Comment by gladky** [comment]
That's the key difference. The flowchart DAQStuck defines partition-problem case (FC3) as the one when TTS state of partition blocking trigger is OOS or ERROR. If it's in BUSY as in flowchart case 6 it's clasified as sth else - in this case fed-stuck (FC5).
