### ISSUE TITLE
request for increasing the threshold for total time to 8%

### ISSUE THREAD

**Issue by andreh12** [cmsdaq/DAQExpert#94]
since in current global running the sound concerning deadtime is played quite frequently (every few minutes) because of a high number of occurrences of spikes in dead time, run coordination asked if we can increase the threshold for the moment.

@mommsen and me propose to increase it to 8%.

As far as I understood is the corresponding quantity to change `Setting.EXPERT_LOGIC_DEADTIME_THESHOLD_TOTAL` corresponding to property `expert.logic.deadtime.threshold.total` (which I however don't know where it comes form).

@gladky  could you please produce a new release with this new threshold, based on release 2.9.1 which is currently in production ?

thanks !

**Comment by gladky** [comment]
@andreh12  It's in configuration file. New release is not required. What needs to be done is to alter this value in 
/daqexpert/conf/pro/expert.properties
```
# LM configuration
expert.logic.deadtime.threshold.fed=5
expert.logic.deadtime.threshold.partition=5
expert.logic.deadtime.threshold.total=5
expert.l1.rate.min=50000
expert.l1.rate.max=100000
```

Should I do it now, during stable-beams?

**Comment by gladky** [comment]
The deadtime is updated each lumisection as you can see on the distribution of more than 1900 deadtime events in August only. (the bucket size is 2, the tail represents 10% of outliers)

![chart 4](https://user-images.githubusercontent.com/1798923/29113746-404da7ae-7cf2-11e7-855b-b828371a2483.png)

Note that all occurrences are located in the area of multiplicity of lumisection period. This means that if we want to introduce the holdoff mentioned in #95 it would have to be at least the duration of one lumisection. We would than have the notifications about the deadtime after almost a minute. 
Is it possible to publish the deadtime in flashlist more frequently? This would then be able to deliver more precise notifications with reasonable latency.

**Comment by mommsen** [comment]
What is actually plotted on the x-axis? Seconds of dead time?

I guess this a question for Jeroen: is the dead time already averages over the whole LS, or is it the dead time of the last N seconds (N<23), only published every LS.

**Comment by gladky** [comment]
X-axis - duration of the occurrences buckets
Y-axis - number of occurrences

**Comment by mommsen** [comment]
Which flashlist / entry are you using for the deadtime?

**Comment by gladky** [comment]
TCDS_CPM_DEADTIMES - columns with prefix deadtime*, in this case: deadtime_beamactive_total and deadtime_total depending on beam mode. The flashlist is in following LAS: 
http://kvm-s3562-1-ip151-95.cms:9945/urn:xdaq-application:service=xmaslas2g

**Comment by mommsen** [comment]
Taking into account Jeroen's answer, that means that we already average the dead time over a whole LS and only warn if it is >5% during this period. In about 50% of the cases in August, this was true for an isolated LS. If we would require 3 LS in sequence. i.e. ~1 minute, it would only warn in ~20% of the cases we have today. I guess it is now up to RC to decide what they want.

**Comment by gladky** [comment]
The deadtime threshold has been updated in production to 8%. Please let me know when you agree with RC what you want to do with the holdoff and let's follow it in the issue #95. Closing this one.

**Comment by andreh12** [comment]
thanks !
