### ISSUE TITLE
Wrong diagnosis of 'FEROL/FEROL40 FIFO stuck'

### ISSUE THREAD

**Issue by mommsen** [cmsdaq/DAQExpert#98]
At 2017-08-22 09:38:27, DAQExpert diagnosed that all DT FEDs are OUT_OF_SYNC, which is correct, but at the same time also reported 'Ferol FIFO stuck', which is wrong. Looking at
http://daq-expert.cms/daq2view-react/index.html?setup=cdaq&time=2017-08-22-09:33:03
you see that the DT FEDs have sent fragments while no triggers were issues (TCDS FED 1024 has 0 events.) These fragments filled up the RU input queues (256 fragments are in ru-c2e15-27-01) and there are no requests (as there were no triggers.) Therefore, the FEDs are back-pressured. 

I think the logic module 'Ferol FIFO stuck' should only trigger if there are requests on the corresponding RU.

**Comment by andreh12** [comment]
#99 was released in 2.9.3, closing this issue.
